codecov:
    require_ci_to_pass: no

coverage:
    precision: 2
    round: down
    range: "70...100"
    status:
        project:
            default:
                target: 0%
                threshold: 100%
        patch:
            default:
                target: 0%
                threshold: 100%

parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no

comment:
    layout: "diff,flags,files,footer"
    behavior: default
    require_changes: no

github_checks:
    annotations: false

ignore:
    - "pyispyb/core/models.py"
