from datetime import datetime

test_proposal = {
    "proposalCode": "MX",
    "title": "Test proposal",
    "proposalType": "MX",
    "personId": 1,
    "proposalId": 1,
    "externalId": None,
    "proposalNumber": "1",
    "bltimeStamp": datetime.strptime("2015-12-21 16:20:43", "%Y-%m-%d %H:%M:%S"),
    "state": "Open",
}


test_data_collection = {
    "binning": 1,
    "bgRadius": None,
    "strategySubWedgeOrigId": None,
    "FOCALSPOTSIZEATSAMPLEY": 20,
    "magnification": None,
    "detectorDistance": 193.087,
    "minDefocus": None,
    "totalExposedDose": None,
    "defocusStepSize": None,
    "detector2Theta": None,
    "nominalMagnification": None,
    "detectorId": None,
    "xtalSnapshotFullPath3": "/dls/i03/data/2016/cm14451-1/jpegs/20160114/tlys_jan_4/tlys_jan_4_1_1_135.0.png",
    "boxSize_CTF": None,
    "c1lens": None,
    "printableForReport": 1,
    "minResolution": None,
    "undulatorGap3": None,
    "dataCollectionGroupId": 988855,
    "slitGapHorizontal": 0.099937,
    "axisStart": 45,
    "xtalSnapshotFullPath1": "/dls/i03/data/2016/cm14451-1/jpegs/20160114/tlys_jan_4/tlys_jan_4_1_1_315.0.png",
    "imageDirectory": "/dls/i03/data/2016/cm14451-1/20160114/tlys_jan_4/",
    "imageSizeY": None,
    "pixelSizeOnImage": None,
    "undulatorGap2": None,
    "resolutionAtCorner": None,
    "voltage": None,
    "startPositionId": None,
    "ACTUALCONTAINERBARCODE": None,
    "BLSAMPLEID": 374695,
    "averageTemperature": None,
    "xBeam": 215.62,
    "actualCenteringPosition": None,
    "amountAstigmatism": None,
    "SESSIONID": 55167,
    "comments": "(-402,345,142) EDNAStrategy4: subWedge:1Aperture: Medium",
    "fileTemplate": "tlys_jan_4_1_####.cbf",
    "DETECTORMODE": None,
    "phasePlate": None,
    "imageSuffix": "cbf",
    "endPositionId": None,
    "c3aperture": None,
    "kappaStart": None,
    "flux": 833107367454.3083,
    "flux_end": None,
    "ACTUALCONTAINERSLOTINSC": None,
    "overlap": 0,
    "wavelength": 1.28255,
    "axisEnd": 0.1,
    "slitGapVertical": 0.059918,
    "beamSizeAtSampleX": 0.05,
    "omegaStart": 45,
    "CRYSTALCLASS": None,
    "endTime": datetime.strptime("2016-01-14 12:41:54", "%Y-%m-%d %H:%M:%S"),
    "particleDiameter": None,
    "extractSize": None,
    "dataCollectionNumber": 1,
    "maxDefocus": None,
    "imagePrefix": "tlys_jan_4",
    "c2lens": None,
    "xtalSnapshotFullPath4": "/dls/i03/data/2016/cm14451-1/jpegs/20160114/tlys_jan_4/tlys_jan_4_1_1_45.0.png",
    "yBeam": 208.978,
    "synchrotronMode": "User",
    "numberOfPasses": 1,
    "chiStart": None,
    "resolution": 1.6,
    "undulatorGap1": 5.685,
    "bestWilsonPlotPath": None,
    "c2aperture": None,
    "datFullPath": None,
    "xtalSnapshotFullPath2": "/dls/i03/data/2016/cm14451-1/jpegs/20160114/tlys_jan_4/tlys_jan_4_1_1_225.0.png",
    "FOCALSPOTSIZEATSAMPLEX": 80,
    "c3lens": None,
    "runStatus": "DataCollection Successful",
    "dataCollectionId": 993677,
    "axisRange": 0.1,
    "nominalDefocus": None,
    "POSITIONID": 595236,
    "numberOfImages": 3600,
    "beamSizeAtSampleY": 0.02,
    "c1aperture": None,
    "transmission": 40.1936,
    "ACTUALSAMPLEBARCODE": None,
    "phiStart": None,
    "beamShape": None,
    "processedDataFile": None,
    "POLARISATION": None,
    "objAperture": None,
    "imageSizeX": None,
    "blSubSampleId": None,
    "experimenttype": None,
    "startImageNumber": 1,
    "ACTUALSAMPLESLOTINCONTAINER": None,
    "rotationAxis": "Omega",
    "exposureTime": 0.02,
    "imageContainerSubPath": None,
    "APERTUREID": 6,
    "centeringMethod": None,
    "totalAbsorbedDose": None,
    "screeningOrigId": None,
    "startTime": datetime.strptime("2016-01-14 12:40:34", "%Y-%m-%d %H:%M:%S"),
}
