from marshmallow import Schema, fields as ma_fields
from flask_restplus import fields
from ispyb import api


data_collection_dict = {
    'dataCollectionId' : fields.Integer(required=True),
    'BLSAMPLEID' : fields.Integer(),
    'SESSIONID' : fields.Integer(),
    'experimenttype' : fields.String(),
    'dataCollectionNumber' : fields.Integer(),
    'startTime' : fields.DateTime(),
    'endTime' : fields.DateTime(),
    'runStatus' : fields.String(),
    'axisStart' : fields.Float(),
    'axisEnd' : fields.Float(),
    'axisRange' : fields.Float(),
    'overlap' : fields.Float(),
    'numberOfImages' : fields.Integer(),
    'startImageNumber' : fields.Integer(),
    'numberOfPasses' : fields.Integer(),
    'exposureTime' : fields.Float(),
    'imageDirectory' : fields.String(),
    'imagePrefix' : fields.String(),
    'imageSuffix' : fields.String(),
    'imageContainerSubPath' : fields.String(),
    'fileTemplate' : fields.String(),
    'wavelength' : fields.Float(),
    'resolution' : fields.Float(),
    'detectorDistance' : fields.Float(),
    'xBeam' : fields.Float(),
    'yBeam' : fields.Float(),
    'comments' : fields.String(),
    'printableForReport' : fields.Integer(),
    'CRYSTALCLASS' : fields.String(),
    'slitGapVertical' : fields.Float(),
    'slitGapHorizontal' : fields.Float(),
    'transmission' : fields.Float(),
    'synchrotronMode' : fields.String(),
    'xtalSnapshotFullPath1' : fields.String(),
    'xtalSnapshotFullPath2' : fields.String(),
    'xtalSnapshotFullPath3' : fields.String(),
    'xtalSnapshotFullPath4' : fields.String(),
    'rotationAxis' : fields.String(),
    'phiStart' : fields.Float(),
    'kappaStart' : fields.Float(),
    'omegaStart' : fields.Float(),
    'chiStart' : fields.Float(),
    'resolutionAtCorner' : fields.Float(),
    'detector2Theta' : fields.Float(),
    'DETECTORMODE' : fields.String(),
    'undulatorGap1' : fields.Float(),
    'undulatorGap2' : fields.Float(),
    'undulatorGap3' : fields.Float(),
    'beamSizeAtSampleX' : fields.Float(),
    'beamSizeAtSampleY' : fields.Float(),
    'centeringMethod' : fields.String(),
    'averageTemperature' : fields.Float(),
    'ACTUALSAMPLEBARCODE' : fields.String(),
    'ACTUALSAMPLESLOTINCONTAINER' : fields.Integer(),
    'ACTUALCONTAINERBARCODE' : fields.String(),
    'ACTUALCONTAINERSLOTINSC' : fields.Integer(),
    'actualCenteringPosition' : fields.String(),
    'beamShape' : fields.String(),
    'dataCollectionGroupId' : fields.Integer(),
    'POSITIONID' : fields.Integer(),
    'detectorId' : fields.Integer(),
    'FOCALSPOTSIZEATSAMPLEX' : fields.Float(),
    'POLARISATION' : fields.Float(),
    'FOCALSPOTSIZEATSAMPLEY' : fields.Float(),
    'APERTUREID' : fields.Integer(),
    'screeningOrigId' : fields.Integer(),
    'startPositionId' : fields.Integer(),
    'endPositionId' : fields.Integer(),
    'flux' : fields.Float(),
    'strategySubWedgeOrigId' : fields.Integer(),
    'blSubSampleId' : fields.Integer(),
    'flux_end' : fields.Float(),
    'bestWilsonPlotPath' : fields.String(),
    'processedDataFile' : fields.String(),
    'datFullPath' : fields.String(),
    'magnification' : fields.Float(),
    'totalAbsorbedDose' : fields.Float(),
    'binning' : fields.Integer(),
    'particleDiameter' : fields.Float(),
    'boxSize_CTF' : fields.Float(),
    'minResolution' : fields.Float(),
    'minDefocus' : fields.Float(),
    'maxDefocus' : fields.Float(),
    'defocusStepSize' : fields.Float(),
    'amountAstigmatism' : fields.Float(),
    'extractSize' : fields.Float(),
    'bgRadius' : fields.Float(),
    'voltage' : fields.Float(),
    'objAperture' : fields.Float(),
    'c1aperture' : fields.Float(),
    'c2aperture' : fields.Float(),
    'c3aperture' : fields.Float(),
    'c1lens' : fields.Float(),
    'c2lens' : fields.Float(),
    'c3lens' : fields.Float(),
    'totalExposedDose' : fields.Float(),
    'nominalMagnification' : fields.Float(),
    'nominalDefocus' : fields.Float(),
    'imageSizeX' : fields.Integer(),
    'imageSizeY' : fields.Integer(),
    'pixelSizeOnImage' : fields.Float(),
    'phasePlate' : fields.Integer(),
    }


class DataCollectionSchema(Schema):
    dataCollectionId = ma_fields.Integer()
    BLSAMPLEID = ma_fields.Integer()
    SESSIONID = ma_fields.Integer()
    experimenttype = ma_fields.String()
    dataCollectionNumber = ma_fields.Integer()
    startTime = ma_fields.DateTime()
    endTime = ma_fields.DateTime()
    runStatus = ma_fields.String()
    axisStart = ma_fields.Float()
    axisEnd = ma_fields.Float()
    axisRange = ma_fields.Float()
    overlap = ma_fields.Float()
    numberOfImages = ma_fields.Integer()
    startImageNumber = ma_fields.Integer()
    numberOfPasses = ma_fields.Integer()
    exposureTime = ma_fields.Float()
    imageDirectory = ma_fields.String()
    imagePrefix = ma_fields.String()
    imageSuffix = ma_fields.String()
    imageContainerSubPath = ma_fields.String()
    fileTemplate = ma_fields.String()
    wavelength = ma_fields.Float()
    resolution = ma_fields.Float()
    detectorDistance = ma_fields.Float()
    xBeam = ma_fields.Float()
    yBeam = ma_fields.Float()
    comments = ma_fields.String()
    printableForReport = ma_fields.Integer()
    CRYSTALCLASS = ma_fields.String()
    slitGapVertical = ma_fields.Float()
    slitGapHorizontal = ma_fields.Float()
    transmission = ma_fields.Float()
    synchrotronMode = ma_fields.String()
    xtalSnapshotFullPath1 = ma_fields.String()
    xtalSnapshotFullPath2 = ma_fields.String()
    xtalSnapshotFullPath3 = ma_fields.String()
    xtalSnapshotFullPath4 = ma_fields.String()
    rotationAxis = ma_fields.String()
    phiStart = ma_fields.Float()
    kappaStart = ma_fields.Float()
    omegaStart = ma_fields.Float()
    chiStart = ma_fields.Float()
    resolutionAtCorner = ma_fields.Float()
    detector2Theta = ma_fields.Float()
    DETECTORMODE = ma_fields.String()
    undulatorGap1 = ma_fields.Float()
    undulatorGap2 = ma_fields.Float()
    undulatorGap3 = ma_fields.Float()
    beamSizeAtSampleX = ma_fields.Float()
    beamSizeAtSampleY = ma_fields.Float()
    centeringMethod = ma_fields.String()
    averageTemperature = ma_fields.Float()
    ACTUALSAMPLEBARCODE = ma_fields.String()
    ACTUALSAMPLESLOTINCONTAINER = ma_fields.Integer()
    ACTUALCONTAINERBARCODE = ma_fields.String()
    ACTUALCONTAINERSLOTINSC = ma_fields.Integer()
    actualCenteringPosition = ma_fields.String()
    beamShape = ma_fields.String()
    dataCollectionGroupId = ma_fields.Integer()
    POSITIONID = ma_fields.Integer()
    detectorId = ma_fields.Integer()
    FOCALSPOTSIZEATSAMPLEX = ma_fields.Float()
    POLARISATION = ma_fields.Float()
    FOCALSPOTSIZEATSAMPLEY = ma_fields.Float()
    APERTUREID = ma_fields.Integer()
    screeningOrigId = ma_fields.Integer()
    startPositionId = ma_fields.Integer()
    endPositionId = ma_fields.Integer()
    flux = ma_fields.Float()
    strategySubWedgeOrigId = ma_fields.Integer()
    blSubSampleId = ma_fields.Integer()
    flux_end = ma_fields.Float()
    bestWilsonPlotPath = ma_fields.String()
    processedDataFile = ma_fields.String()
    datFullPath = ma_fields.String()
    magnification = ma_fields.Float()
    totalAbsorbedDose = ma_fields.Float()
    binning = ma_fields.Integer()
    particleDiameter = ma_fields.Float()
    boxSize_CTF = ma_fields.Float()
    minResolution = ma_fields.Float()
    minDefocus = ma_fields.Float()
    maxDefocus = ma_fields.Float()
    defocusStepSize = ma_fields.Float()
    amountAstigmatism = ma_fields.Float()
    extractSize = ma_fields.Float()
    bgRadius = ma_fields.Float()
    voltage = ma_fields.Float()
    objAperture = ma_fields.Float()
    c1aperture = ma_fields.Float()
    c2aperture = ma_fields.Float()
    c3aperture = ma_fields.Float()
    c1lens = ma_fields.Float()
    c2lens = ma_fields.Float()
    c3lens = ma_fields.Float()
    totalExposedDose = ma_fields.Float()
    nominalMagnification = ma_fields.Float()
    nominalDefocus = ma_fields.Float()
    imageSizeX = ma_fields.Integer()
    imageSizeY = ma_fields.Integer()
    pixelSizeOnImage = ma_fields.Float()
    phasePlate = ma_fields.Integer()
