name: Deploy documentation
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  pip install mkdocs
                  pip install mkdocs-material

            - name: Build
              run: |
                  mkdocs build --strict --verbose

            - name: Create OpenAPI spec
              run: |
                  pip install -r requirements.txt
                  pip install -e . --no-deps
                  cp tests/core/auth.yml auth.yml
                  python scripts/generate_apispec.py

            - name: Run redoc
              uses: seeebiii/redoc-cli-github-action@v10
              with:
                args: 'bundle -o api/index.html openapi.json'

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.3.0
              with:
                  branch: gh-pages
                  folder: public
