name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Run flake8
        uses: py-actions/flake8@v2
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black
        uses: psf/black@stable
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit
        uses: tj-actions/bandit@v5.1
