name: Lint

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  pip install tox
            - name: Analysing the code with flake8
              run: |
                  tox -e flake8
    style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: psf/black@stable
